---
title: "team"
author: "Matthew Coulibaly Github: MattCoulibaly Jessie Bustin Github:jebustin"
date: "4/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)
per <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)
library("dplyr")
library("ggplot2")
```

```{r}
# Question 1
table(acc$DAY_WEEK)
```
# Day 7 of the week has the most accidents in the dataframe with 5873 accidents. The next closes days are day 1 and day 6 with 5360 and 5358 accidents respectively. The rest of the days have less than 4700 accidents.

```{r}
# Question 2
barplot(table(acc$HOUR))
```

# Most accidents in this dataframe occur between hour 17 and hour 22.

```{r}
# Question 3
nrow(acc[acc$DRUNK_DR >= 1,])
```
# There were 8769 accidents with at least one drunk driver in this dataframe

```{r}
# Question 4
per1 = per[per$PER_TYP == 1,]
```

```{r}
# Question 5
merge <- left_join(per, acc, by = "ST_CASE")
```

```{r}
# Question 6
merge <- merge %>%
  filter(HOUR.x, HOUR.x < 25) %>%
  filter(SEX, SEX <= 2) %>%
  mutate(SEX = as.factor(SEX)) %>%
  mutate(DAY_WEEK = as.factor(DAY_WEEK))

levels(merge$SEX) <- c("Male", "Female")
levels(merge$DAY_WEEK) <- c("Sunday", "Monday", "Tuesday",
                            "Wednesday", "Thursday", "Friday",
                            "Saturday")

merge %>%
  group_by(DAY_WEEK, HOUR.x, SEX) %>%
  summarize(count = length(unique(ST_CASE))) %>%
  ggplot(aes(x = HOUR.x, y = count, color = SEX)) +
  geom_line() +
  facet_wrap(~DAY_WEEK)
```

# Question 7 & 8


# Question 9
```